### ISSUE TITLE
is this package DEAD ?

### ISSUE THREAD

**Issue by achtan** [reactjs/react-meteor#28]
is this package DEAD ?

**Comment by benjamn** [comment]
Not dead, I just haven't had much time to maintain it recently. Now that I work for Meteor instead of Facebook, it's probably time I pitched this project to my team as something we are serious about maintaining. Of course we (Meteor) have our own templating framework, [Blaze](https://www.meteor.com/blaze), and supporting that is a higher priority than supporting React, but I don't think the two have to be mutually exclusive.

Anyway, thanks for the challenge ;)

**Comment by akuckartz** [comment]
Thanks for the quick reply.

**Comment by achtan** [comment]
sure, i'm just looking for meteor component solution...
and React has a good approach, but i don't mind if Blaze will implement components as well (i think that will be even better)


https://github.com/meteor/meteor/blob/devel/packages/blaze/README.md#future-work

**Comment by ccorcos** [comment]
The thing that really attracts me about React is that everything comes down to programming as opposed to markup. Blaze is great at what it does, but I've struggled to get to the next level of abstraction because I'm limited to the markup and helpers.

**Comment by MaazAli** [comment]
Would love to see more updates to this to bring it up to speed with the latest release of meteor.
