### ISSUE TITLE
What is _meteorStateQueue?

### ISSUE THREAD

**Issue by ccorcos** [reactjs/react-meteor#39]
Whats going on here?
https://github.com/reactjs/react-meteor/blob/master/src/ReactMeteor.js#L70

**Comment by benjamn** [comment]
If a bunch of Meteor state changes are triggered at once, we want to combine those states into one object and call `this.setState` once, rather than calling `this.setState` for every change. The `_meteorStateQueue` array is where those multiple states are stored, so that the `Meteor.setTimeout` function can combines them together and call `component.setState` after a brief delay (16 milliseconds).

**Comment by ccorcos** [comment]
ahhh, now I get what you're doing there. A little confusing with the splice, unshift, extend pattern. Its hard to realize that everything ends up in combinedState. Clever though.

If setState is getting called a bunch of times, isn't it safe to say that its because of reactive computations being run? Perhaps a more appropriate implementation would be Tracker.afterflush

http://docs.meteor.com/#/full/tracker_afterflush

**Comment by ccorcos** [comment]
Check out this example in your console:

```js

var a = {}
var b = new ReactiveVar(1);
var c = new ReactiveVar(2);

var needsUpdate = new Tracker.Dependency()

Tracker.autorun(function(){
  a.b = b.get()
  needsUpdate.changed()
})
Tracker.autorun(function(){
  a.c = c.get()
  needsUpdate.changed()
})

Tracker.autorun(function(c){
  needsUpdate.depend()
  Tracker.afterFlush(function() {
    console.log("update", a)
  })
})


// try just one at a time
b.set(3)



// then try this one
c.set(4)




// now try both of these
b.set(5)
c.set(6)

```
